#!/usr/bin/env zsh

# WSL 1 or 2
if (( ${+commands[xdg-open]} )); then
  xdg-open $@
elif (( ${+commands[termux-open]} )); then
  termux-open $@
elif [[ $OSTYPE == darwin* ]]; then
  command open $@
elif [[ $OSTYPE == cygwin* ]]; then
  cygstart $@
elif [[ $OSTYPE == linux* && -r /proc/version &&
    $(< /proc/version) == *[Mm]icrosoft* ]]; then
  explorer.exe $@
elif [[ $OSTYPE == msys ]]; then
  explorer.exe $(cygpath -w $@)
fi
