#!/usr/bin/env zsh

if (( ${+commands[xclip]} )); then
  xclip -selection clipboard -in
elif (( ${+commands[xsel]} )); then
  xsel -b
elif (( ${+commands[wl-copy]} )); then
  wl-copy
elif (( ${+commands[termux-clipboard-set]} )); then
  termux-clipboard-set
# WSL 1 or 2
elif [[ $OSTYPE == linux* && -r /proc/version && $(< /proc/version) == *[Mm]icrosoft* ]]; then
    clip.exe
elif [[ $OSTYPE == darwin* ]]; then
  command pbcopy
elif [[ $OSTYPE == (cygwin*|msys) ]]; then
  tee > /dev/clipboard
fi
