#!/usr/bin/env zsh

if (( $+commands[xclip] )); then
  xclip -selection clipboard -out
if (( $+commands[xsel] )); then
  xsel -b
elif [[ "$OSTYPE" == darwin* ]]; then
  command pbpaste
elif [[ "$OSTYPE" == (cygwin*|msys) ]]; then
  cat /dev/clipboard
elif [[ $OSTYPE == linux* ]] && [[ -r /proc/version ]] && [[ $(< /proc/version) == *microsoft* ]]; then
  # WSL
  powershell.exe -Command Get-Clipboard
fi
